# C/C++ with GCC
# Build your C/C++ project with GNU GCC.
# https://docs.microsoft.com/vsts/pipelines/apps/c-cpp/gcc

queue: 'Hosted Ubuntu 1604'
steps:

  - script: ./configure
    displayName: 'configure'

  - script: 'make'
    displayName: 'make'

  - script: 'make test'
    displayName: 'make test'

# For information on extending this YAML to:
# - Save the artifacts of this build with the build record
# See https://docs.microsoft.com/vsts/pipelines/apps/c-cpp/gcc